version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000" # Port for main app testing
    volumes:
      - ./app:/code/app # Moiunt locally for testing
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/engagementdb
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload # --reload for dev

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports: 
      - "5432:5432" # expose DB port for access
    environment:
      - POSTGRES_USER=user       #CHANGE THIS LATER!!!, it should be named in the .env or randomly generated
      - POSTGRES_PASSWORD=password #CHANGE THIS LATER!!!, it should be named in the .env or randomly generated
      - POSTGRES_DB=engagementdb

volumes:
  postgres_data: 