version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000" # Port for main app testing
    volumes:
      - ./app:/code/app # Moiunt locally for testing
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/engagementdb
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload # --reload for dev

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports: 
      - "5432:5432" # expose DB port for access
    environment:
      - POSTGRES_USER=user       #CHANGE THIS LATER!!!, it should be named in the .env or randomly generated
      - POSTGRES_PASSWORD=password #CHANGE THIS LATER!!!, it should be named in the .env or randomly generated
      - POSTGRES_DB=engagementdb

  limesurvey:
    image: docker.io/martialblog/limesurvey:latest
    ports:
      - "8080:8080" # LimeSurvey web interface
    environment:
      - DB_TYPE=pgsql
      - DB_HOST=limesurvey_db
      - DB_PORT=5432
      - DB_USERNAME=limesurvey_user
      - DB_PASSWORD=limesurvey_password
      - DB_DATABASE=limesurvey
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin123
      - ADMIN_NAME=Administrator
      - ADMIN_EMAIL=admin@example.com
      - PUBLIC_URL=http://localhost:8080
    depends_on:
      - limesurvey_db
    volumes:
      - limesurvey_data:/var/lib/limesurvey/upload
      - limesurvey_plugins:/var/lib/limesurvey/plugins
      - ./limesurvey-config.php:/var/www/html/application/config/config.php:ro

  limesurvey_db:
    image: postgres:15-alpine
    volumes:
      - limesurvey_postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432" # Different port to avoid conflict with main DB
    environment:
      - POSTGRES_USER=limesurvey_user
      - POSTGRES_PASSWORD=limesurvey_password
      - POSTGRES_DB=limesurvey

volumes:
  postgres_data:
  limesurvey_data:
  limesurvey_plugins:
  limesurvey_postgres_data: 